# Generated by Django 4.0.2 on 2022-03-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(1, 'community'), (2, 'professional'), (3, 'business')], default=1),
        ),
    ]
