# Generated by Django 3.2 on 2022-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220425_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='number_of_logged_in_user',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='number_of_logins',
            field=models.IntegerField(default=0),
        ),
    ]
