# Generated by Django 3.2 on 2022-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_useractivity_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='number_of_logins',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
