# Generated by Django 3.2 on 2022-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_useractivity_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
