# Generated by Django 3.2 on 2022-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220426_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device',
            field=models.TextField(blank=True, null=True),
        ),
    ]
