# Generated by Django 4.0.2 on 2022-02-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0006_alter_basedevice_demo'),
        ('block', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='block',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='block',
            name='screenshots',
            field=models.ManyToManyField(related_name='block_screenshots', to='AI.MediaFile'),
        ),
    ]
