# Generated by Django 4.0.2 on 2022-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_review_isfeatured_review_is_featured'),
        ('block', '0003_alter_block_cover_image_alter_block_demo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='block',
            name='download',
        ),
        migrations.RemoveField(
            model_name='block',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='block',
            name='review',
        ),
        migrations.AddField(
            model_name='block',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='reviews',
            field=models.ManyToManyField(related_name='block_reviews', to='users.Review'),
        ),
    ]
