# Generated by Django 3.2 on 2022-06-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_alter_block_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
