# Generated by Django 3.2 on 2022-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_useractivity_device'),
        ('block', '0006_auto_20220612_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='block_reviews', to='users.Review'),
        ),
    ]
