# Generated by Django 3.2 on 2022-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0008_alter_block_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='block',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='demo/'),
        ),
    ]
