# Generated by Django 4.0.2 on 2022-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancled',
            field=models.BooleanField(default=False),
        ),
    ]
