# Generated by Django 4.0.2 on 2022-03-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_cancled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cancled',
            new_name='canceled',
        ),
    ]
