# Generated by Django 4.0.2 on 2022-02-25 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0006_alter_basedevice_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0002_remove_extention_cover_extention_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extention',
            new_name='Extension',
        ),
    ]
