# Generated by Django 4.0.2 on 2022-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_rename_extention_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='rating',
        ),
        migrations.AddField(
            model_name='extension',
            name='average_rating',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
    ]
