# Generated by Django 3.2 on 2022-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_useractivity_device'),
        ('extensions', '0005_auto_20220525_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='extension_reviews', to='users.Review'),
        ),
    ]
