# Generated by Django 4.0.2 on 2022-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
