# Generated by Django 4.0.2 on 2022-02-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_alter_basedevice_cover_image_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_cover_image', to='AI.mediafile'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
