# Generated by Django 4.0.2 on 2022-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0005_alter_basedevice_cover_image_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
