# Generated by Django 4.0.2 on 2022-03-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0006_alter_basedevice_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='basedevice',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='demo/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
