# Generated by Django 4.0.2 on 2022-03-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_review'),
        ('AI', '0007_alter_basedevice_cover_image_alter_basedevice_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedevice',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basedevice',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.review'),
        ),
    ]
