# Generated by Django 4.0.2 on 2022-03-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0008_basedevice_average_rating_alter_basedevice_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedevice',
            name='rating',
        ),
    ]
