# Generated by Django 4.0.2 on 2022-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_review_rate_review_rating'),
        ('AI', '0009_remove_basedevice_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedevice',
            name='review',
        ),
        migrations.AddField(
            model_name='basedevice',
            name='reviews',
            field=models.ManyToManyField(related_name='device_reviews', to='users.Review'),
        ),
    ]
