# Generated by Django 4.0.2 on 2022-03-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0010_remove_basedevice_review_basedevice_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedevice',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='basedevice',
            name='download',
        ),
    ]
