# Generated by Django 4.0.2 on 2022-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0011_remove_basedevice_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='average_rating',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
    ]
