# Generated by Django 3.2 on 2022-05-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0012_alter_basedevice_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='basedevice',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basedevice',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
