# Generated by Django 3.2 on 2022-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_useractivity_device'),
        ('AI', '0013_auto_20220502_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedevice',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='device_reviews', to='users.Review'),
        ),
    ]
