# Generated by Django 3.2 on 2022-07-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0016_basedevice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedevice',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='basedevice',
            name='domo_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='basedevice',
            name='summary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
